[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
providers = ["python"]

[deploy]
startCommand = "python start_services.py --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
PYTHON_VERSION = "3.11"
NIXPACKS_PYTHON_VERSION = "3.11"