[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
providers = ["python"]

[deploy]
startCommand = "python simple_server.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
PYTHON_VERSION = "3.11"
NIXPACKS_PYTHON_VERSION = "3.11"