name: Update Taiwan PK10 Data

on:
  schedule:
    # 每10分钟运行一次（台湾PK10开奖频率较高）
    - cron: '*/10 * * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Update Taiwan PK10 Data
      run: |
        # 调用Vercel部署的更新API
        curl -X GET "https://${{ secrets.VERCEL_DOMAIN }}/api/update-taiwan-pk10?token=${{ secrets.UPDATE_TOKEN }}" \
          -H "Content-Type: application/json" \
          -H "User-Agent: GitHub-Actions-Bot" \
          --fail-with-body \
          --show-error \
          --silent
        
        echo "Data update completed at $(date)"
    
    - name: Log Update Status
      if: always()
      run: |
        echo "Update job finished with status: ${{ job.status }}"
        echo "Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"